# Generated by Django 2.1.5 on 2019-01-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(db_column='student_id', primary_key=True, serialize=False)),
                ('student_no', models.IntegerField(db_column='student_no')),
                ('student_name', models.CharField(db_column='student_name', max_length=20)),
            ],
            options={
                'db_table': 'all_student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(db_column='subject_id', primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_column='subject_name', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'all_subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectElective',
            fields=[
                ('subject_elective_id', models.IntegerField(db_column='subject_elective_id', primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_web.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_web.Subject')),
            ],
            options={
                'db_table': 'all_subject_elective',
            },
        ),
    ]
